### ISSUE TITLE
Doesn't work with Puppet 3.4

### ISSUE THREAD

**Issue by delwaterman** [voxpupuli/puppet-windows_firewall#10]
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class windows_firewall at
E:/infrastructure/configuration/tableau_server.pp:132 on node win2008r2x64.corp.intentmedia.com
Wrapped exception:
Could not find declared class windows_firewall
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class windows_firewall at
E:/infrastructure/configuration/tableau_server.pp:132 on node win2008r2x64.corp.intentmedia.com

**Comment by waqark3389** [comment]
@liamjbennett I am facing this exact issue. Here is the error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class windows_firewall at /etc/puppet/environments/testing/modules/win-firewall/manifests/init.pp:2 on node testing-win
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

All Ive done is created a module called win-firewall which has the contents: 

class win-firewall {
class { 'windows_firewall': ensure => 'running' }
}

Then I do include win-firewall on the node.
