### ISSUE TITLE
v3.0.0 doesn't support multiple ports in local_port

### ISSUE THREAD

**Issue by rychannel** [voxpupuli/puppet-windows_firewall#110]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2019.8.3
- Ruby:
- Distribution: Windows Server 2016/2019
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)

```
  windows_firewall::exception { 'AWD AFT':
    ensure       => present,
    direction    => 'in',
    action       => 'allow',
    enabled      => true,
    protocol     => 'TCP',
    local_port   => '2000,2010',
    remote_port  => 'any',
    display_name => 'AWD AFT (Added by Puppet)',
    description  => 'AWD AFT (Added by Puppet)',
  }


  windows_firewall::exception { 'IBM Websphere 50000 60000':
    ensure       => absent,
    direction    => 'in',
    action       => 'allow',
    enabled      => true,
    protocol     => 'TCP',
    local_port   => '50000-60000',
    remote_port  => 'any',
    display_name => 'IBM Websphere Added by Puppet)',
    description  => 'IBM Websphere (Added by Puppet)',
  }
```

## What are you seeing

Evaluation Error: Error while evaluating a Resource Statement, Windows_firewall::Exception[IBM Websphere]: parameter 'local_port' expects a value of type Undef, Integer, or Enum, got Tuple.

This use to work until I installed the new module.
## What behaviour did you expect instead

Accept the input and apply the rule

**Comment by kenyon** [comment]
Duplicates #80
