### ISSUE TITLE
Add simple disabling of individual firewall profiles

### ISSUE THREAD

**Issue by cwb124** [voxpupuli/puppet-windows_firewall#19]
I'd like to see the ability to just disable firewall profiles with this module.  Stopping the service is not always a good alternative for simply disabling firewall profiles, especially if you want to disable only one or two of the available three.  Something like:

firewall::profile { "Public":
    profile => "Public",
    ensure => disabled,
    }

**Comment by rismoney** [comment]
i have a fix for this pending...

**Comment by claflico** [comment]
:+1: 

It appears that the firewall state and rules only work for the Domain profile but when the server isn't on a domain they don't take affect.

**Comment by liamjbennett** [comment]
The fix for this was merge in #27
