### ISSUE TITLE
fixing remote ports

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/puppet-windows_firewall#22]
From Scott Kasai:

We were tasked to setup a block of using HTTP/HTTPS and SSH.  Your code
would only block the local ports, but when we want to block the use of
HTTP/HTTPS and SSH, you can't use your code because the local ports
don't go THROUGH 80/443 or 22.  They use other ports to try and connect
to REMOTE ports.

The following is the code hack I did with your exceptions.pp:

```
56a57
 > #     remote_port  => '9999',
81a83
 >   $remote_port = '',
95a98
 >           $port_param2 = 'port'
98a102
 >           $port_param2 = 'remoteport'
106,107c110,128
<         $allow_context = "protocol=${protocol}
${port_param}=${local_port}"
<         validate_re($local_port,['any|[0-9]{1,5}'])

---
 >         # Check for Port Define to format $allow_context properly to
avoid erroring
 >         # out when issuing the netsh command. -- SKasai
 >         if ($local_port != '') and ($remote_port == '') {
 >           $allow_context = "protocol=${protocol}
${port_param}=${local_port}"
 >         }
 >         elsif ($local_port == '') and ($remote_port != '') {
 >           $allow_context = "protocol=${protocol}
${port_param2}=${remote_port}"
 >         }
 >         else {
 >             $allow_context = "protocol=${protocol}
${port_param}=${local_port} ${port_param2}=${remote_port}"
 >         }
 >         # Validate port define if it is something other than '',
otherwise code
 >         # will error out due to being undefined. -- SKasai
 >         if $local_port != '' {
 >           validate_re($local_port,['any|[0-9]{1,5}'])
 >         }
 >         if $remote_port != '' {
 >           validate_re($remote_port,['any|[0-9]{1,5}'])
 >         }
```

What I did here is add the additional support for remote_port, so in the
case of setting up firewall blocks to go to a specific port on another
machine, this should cover that portion.

This will now allow, in the case of institutions where they would like
to block ports like HTTP/HTTPS, SSH or other connections to other
machines for things like finals in our case or machines where you want
to prevent machines making connection to other machines to specific ports.

**Comment by nabber00** [comment]
Yes I'd like a remote_port parameter too!

**Comment by ofalk** [comment]
Old issue. remote_port can be specified in the current version. I'd say this issue can be closed.
