### ISSUE TITLE
Missing dependency puppetlabs-registry in PuppetForge version.

### ISSUE THREAD

**Issue by aimonb** [voxpupuli/puppet-windows_firewall#29]
This module requires puppetlabs-registry module. It throws an error if it is not available. Please add to dependencies. Error: "Invalid resource type registry_value"

**Comment by aimonb** [comment]
Ah see that latest in repo has this dependency. The one in Puppet Forge does not.  Please release new version to the forge.

**Comment by spotter-puppet** [comment]
newest version says needs puppet-registry < 3.0.0, but standard version is 3.0.0 and appears to support properly

**Comment by dhoppe** [comment]
Could you please provide a pull request?
