### ISSUE TITLE
liamjbennett/win_facts module causes Registry errors

### ISSUE THREAD

**Issue by claflico** [voxpupuli/puppet-windows_firewall#34]
Upgraded to 1.0.3 of the module which added the liamjbennett/win_facts requirement. That module causes puppet not to run and claims an error in the puppetlabs/wsus_client module: Parameter path failed on Registry_key[HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate: Munging failed for value::....

I remove that module and the error goes away.

**Comment by ofalk** [comment]
The dep on win_facts is already removed in my current version, it's just not merged yet.
https://github.com/ofalk/puppet-windows_firewall/commit/0f70974e6b92df786019f4b4bba50b600e9b2161

**Comment by ofalk** [comment]
Merged now: https://github.com/voxpupuli/puppet-windows_firewall/pull/61
