### ISSUE TITLE
Dropping some old operatingsystem versions

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-windows_firewall#64]
I was about to work on #45 and noticed that this module has some really old versions of windows being used within it.  This is going to be a huge problem for people who want to update and contribute to this module.

Anyone have any objections to limiting the scope of this module to only the following operating systems:
- Windows 10
- Windows Server 2008R2
- Windows Server 2012R2
- Windows Server 2012
- Windows Server 2016

/cc @alexjfisher @bastelfreak

**Comment by alexjfisher** [comment]
If you mean these https://github.com/voxpupuli/puppet-windows_firewall/blob/master/manifests/init.pp#L34 then yeah, I think that's fair enough to drop them.

**Comment by ofalk** [comment]
@TraGicCode I'm with you. Since W2K3(R2) as well as WinXP are out of support (by Microsoft), I think we can drop it. Why should we support unsupported OSes. :smile:
(Well, I know W2K8 is also EOL, but I also know, that it's still widely used; Esp. in enterprise environments, where it's also likely, people use Puppet.)

**Comment by nabber00** [comment]
Sounds good to me.  Also on a related note, update metadata.json accordingly.  Windows 10 and Server 2016 are currently missing.  I believe that is supposed to be the "authoritative" source for what OS versions are supported by the module.

**Comment by bastelfreak** [comment]
@nabber00 correct, the metadata.json is authoritative. Are you interested in providing a patch for it that updates the list of supported operating systems? Or @TraGicCode?

**Comment by TraGicCode** [comment]
@bastelfreak ,

Wish i could but i have been really swamped lately.

**Comment by nabber00** [comment]
Patch for module version 2.0.0:

```
Index: metadata.json
===================================================================
--- metadata.json       (revision 226)
+++ metadata.json       (working copy)
@@ -26,10 +26,11 @@
     {
       "operatingsystem": "windows",
       "operatingsystemrelease": [
-        "2008",
+        "2016",
         "2008 R2",
         "2012",
-        "2012 R2"
+        "2012 R2",
+        "10"
       ]
     }
   ],
```

**Comment by nabber00** [comment]
Looks like this also means we can remove references to operatingsystemversion that are used to handle no longer supported versions of Windows.  This means the dependency on the liamjbennett-win_facts module for operatingsystemversion fact can be removed along with those checks.

**Comment by nabber00** [comment]
#48 Should be easy to address at the same time.
