### ISSUE TITLE
Documentation is not updated for new puppet 4 data types

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-windows_firewall#65]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: N/A
- Distribution: N/A
- Module version: master branch

## How to reproduce (e.g Puppet code you use)
Use the example in the readme.

```puppet
windows_firewall::exception { 'WINRM':
  ensure       => present,
  direction    => 'in',
  action       => 'allow',
  enabled      => 'yes',
  protocol     => 'TCP',
  local_port   => 5985,
  remote_port  => 'any',
  display_name => 'Windows Remote Management HTTP-In',
  description  => 'Inbound rule for Windows Remote Management via WS-Management. [TCP 5985]',
}
```

## What are you seeing
An error because a datatype/breaking change happened.

## What behaviour did you expect instead
It to work!

## Output log
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Windows_firewall::Exception[WINRM]: parameter 'ena
bled' expects a Boolean value, got String (file: C:/Users/vagrant/Desktop/test.pp, line: 1) on node win-vmro6vss08u.local
```

## Any additional information you'd like to impart
This happened when #61 got merged.

**Comment by alexjfisher** [comment]
Looks like this was fixed in https://github.com/voxpupuli/puppet-windows_firewall/pull/81
