### ISSUE TITLE
Master O/S conditionals Completely Broken

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-windows_firewall#66]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: N/A
- Distribution: N/A
- Module version: master branch

## How to reproduce (e.g Puppet code you use)
Use this resource

```puppet
windows_firewall::exception { 'WINRM':
  ensure       => present,
  direction    => 'in',
  action       => 'allow',
  enabled      => true,
  protocol     => 'TCP',
  local_port   => 5985,
  remote_port  => 'any',
  display_name => 'Windows Remote Management HTTP-In',
  description  => 'Inbound rule for Windows Remote Management via WS-Management. [TCP 5985]',
}
```

## What are you seeing
Indication that the operatingsystemversion variable is undefined.

## Output log

```
Warning: Unknown variable: '::operatingsystemversion'. (file: C:/Users/vagrant/windows_firewall/manifests/exception.pp,
line: 97, column: 12)
```

## Any additional information you'd like to impart
For some reason #61 removed the win_facts module yet this module is using a fact ( operatingsystemversion ) from that module.  When it was removed the code wasn't correctly adjusted/fixed so essentially this module is broken i would assume for certain cross platform support it had previously.

/cc @ghoneycutt

**Comment by juniorsysadmin** [comment]
Can we not come up with a replacement using modern facter facts? liamjbennett/win_facts has not been maintained for quite some time.

**Comment by nabber00** [comment]
Since this module now requires Windows Server 2008 or newer, operatingsystemversion should no longer be needed as all the checks I can see in the code are for handling older versions.

**Comment by ofalk** [comment]
Hi!
Can you please try out the latest version and let us know if that works better for you?
