### ISSUE TITLE
Update puppetlabs-registry module dependency

### ISSUE THREAD

**Issue by nabber00** [voxpupuli/puppet-windows_firewall#72]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.1
- Ruby: 2.3.1
- Distribution: Ubuntu 16.04
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)
/opt/puppetlabs/bin/puppet module install puppet-windows_firewall
/opt/puppetlabs/bin/puppet module upgrade puppetlabs-registry --force
/opt/puppetlabs/bin/puppet module list

## What are you seeing

Warning: Module 'puppetlabs-registry' (v2.0.1) fails to meet some dependencies:
  'puppet-windows_firewall' (v2.0.0) requires 'puppetlabs-registry' (>= 1.1.1 < 2.0.0)

## What behaviour did you expect instead

No warning from puppet-windows_firewall module

## Output log

N/A

## Any additional information you'd like to impart

puppetlabs-registry module has now advanced to v2.x.  Please update puppet-windows_firewall to accommodate this new version.

**Comment by juniorsysadmin** [comment]
#74
