### ISSUE TITLE
remote_port and local_port should also support string for comma-separated port list or dash-separated port range.

### ISSUE THREAD

**Issue by jmchenra** [voxpupuli/puppet-windows_firewall#80]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.x
- Ruby: 2.4.x
- Distribution: PE 2018.1
- Module version: 2.0.1

## How to reproduce (e.g Puppet code you use)
Assign local_port or remote_port a string containing comma-separated port number list (i.e. '80, 8080, 8081') or dash-separated port range ('8080-8089').
## What are you seeing
String type is not allowed for local_port and remote_port
## What behavior did you expect instead
Should be allowed
## Output log
parameter 'local_port' expects a value of type Undef, Integer[1, 65535], or Enum['any'], got String

**Comment by rychannel** [comment]
Just upgraded to 3.0.0 and multiple ports don't work in a rule. Had to rewrite all of my firewall rules in puppet with single port number rules, had to stop enforcing some rules altogether.  Would be great if this functionality could be re-added.
